### ISSUE TITLE
TARDISBANK_KEY environment variable

### ISSUE THREAD

**Issue by rienafairefr** [TardisBank/TardisBank#39]
I tried to run tardisbank.
It's not really documented that the TARDISBANK_KEY variable (used for encryption) must  be a base64. `Convert.FromBase64String` is run on the value, and fails hard if it's not a base64-encoded value.

**Comment by rienafairefr** [comment]
The length of that variable is also not documented, the example one is a guide (32 characters in base64 work, but longer or shorter seems to fail), but it's after trials and errors I managed

**Comment by mikehadlow** [comment]
Hi @rienafairefr 
Check out the GenerateKeyFile unit test here:
https://github.com/TardisBank/TardisBank/blob/master/server/src/TardisBank.UnitTests/AuthenticationTests.cs#L20
If you run that test you'll create a file with a valid TARDISBANK_KEY variable.
