### ISSUE TITLE
Move TardisBank to a TardisBank organisation?

### ISSUE THREAD

**Issue by mikehadlow** [TardisBank/TardisBank#7]
Hi @keithbloom, what do you say we move TardisBank out of my GitHub and host it in it's own organisation? Then we can both be equal owners?

**Comment by keithbloom** [comment]
Hi @mikehadlow, if it not too much effort I guess that would make sense. :+1:

**Comment by keithbloom** [comment]
Going to close this @mikehadlow as you have now done it :shipit:
